#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BackpackComponent

#include "Basic.hpp"

#include "Flame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BackpackComponent.BP_BackpackComponent_C
// 0x0000 (0x0EF0 - 0x0EF0)
class UBP_BackpackComponent_C final : public UBackpackComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BackpackComponent_C">();
	}
	static class UBP_BackpackComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BackpackComponent_C>();
	}
};
//(alignof(UBP_BackpackComponent_C) == 0x000010, "Wrong alignment on UBP_BackpackComponent_C");
//(sizeof(UBP_BackpackComponent_C) == 0x000EF0, "Wrong size on UBP_BackpackComponent_C");

}

