#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Boat_Trailer_01

#include "Basic.hpp"

#include "BP_Car_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Boat_Trailer_01.BP_Boat_Trailer_01_C
// 0x0008 (0x05A8 - 0x05A0)
class ABP_Boat_Trailer_01_C final : public ABP_Car_Base_C
{
public:
	class UObstacleComponent*                     Obstacle;                                          // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Boat_Trailer_01_C">();
	}
	static class ABP_Boat_Trailer_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Boat_Trailer_01_C>();
	}
};
static_assert(alignof(ABP_Boat_Trailer_01_C) == 0x000008, "Wrong alignment on ABP_Boat_Trailer_01_C");
static_assert(sizeof(ABP_Boat_Trailer_01_C) == 0x0005A8, "Wrong size on ABP_Boat_Trailer_01_C");
static_assert(offsetof(ABP_Boat_Trailer_01_C, Obstacle) == 0x0005A0, "Member 'ABP_Boat_Trailer_01_C::Obstacle' has a wrong offset!");

}

