#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChallengeCondition_TravelDistanceWithAirdrop

#include "Basic.hpp"

#include "BP_ChallengeCondition_TravelDistanceWithAirdrop_classes.hpp"
#include "BP_ChallengeCondition_TravelDistanceWithAirdrop_parameters.hpp"


namespace SDK
{

// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.ExecuteUbergraph_BP_ChallengeCondition_TravelDistanceWithAirdrop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::ExecuteUbergraph_BP_ChallengeCondition_TravelDistanceWithAirdrop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "ExecuteUbergraph_BP_ChallengeCondition_TravelDistanceWithAirdrop");

	Params::BP_ChallengeCondition_TravelDistanceWithAirdrop_C_ExecuteUbergraph_BP_ChallengeCondition_TravelDistanceWithAirdrop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.ResetDistance
// (BlueprintCallable, BlueprintEvent)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::ResetDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "ResetDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.PickedUpAirdrop
// (BlueprintCallable, BlueprintEvent)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::PickedUpAirdrop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "PickedUpAirdrop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.Distance Updated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Distance_Increment                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::Distance_Updated(float Distance_Increment)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "Distance Updated");

	Params::BP_ChallengeCondition_TravelDistanceWithAirdrop_C_Distance_Updated Parms{};

	Parms.Distance_Increment = Distance_Increment;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.Get Maximum Progress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   Maximum_Progress                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::Get_Maximum_Progress(int32* Maximum_Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "Get Maximum Progress");

	Params::BP_ChallengeCondition_TravelDistanceWithAirdrop_C_Get_Maximum_Progress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Maximum_Progress != nullptr)
		*Maximum_Progress = Parms.Maximum_Progress;
}


// Function BP_ChallengeCondition_TravelDistanceWithAirdrop.BP_ChallengeCondition_TravelDistanceWithAirdrop_C.Get Condition Text
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             Condition_Text                                         (Parm, OutParm)

void ABP_ChallengeCondition_TravelDistanceWithAirdrop_C::Get_Condition_Text(class FText* Condition_Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChallengeCondition_TravelDistanceWithAirdrop_C", "Get Condition Text");

	Params::BP_ChallengeCondition_TravelDistanceWithAirdrop_C_Get_Condition_Text Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Condition_Text != nullptr)
		*Condition_Text = std::move(Parms.Condition_Text);
}

}

