#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemTransferMapping

#include "Basic.hpp"

#include "Flame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItemTransferMapping.BP_ItemTransferMapping_C
// 0x0000 (0x0078 - 0x0078)
class UBP_ItemTransferMapping_C final : public UInventoryActionMapping
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ItemTransferMapping_C">();
	}
	static class UBP_ItemTransferMapping_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ItemTransferMapping_C>();
	}
};
static_assert(alignof(UBP_ItemTransferMapping_C) == 0x000008, "Wrong alignment on UBP_ItemTransferMapping_C");
static_assert(sizeof(UBP_ItemTransferMapping_C) == 0x000078, "Wrong size on UBP_ItemTransferMapping_C");

}

