#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MapTool_Tutorial

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_MapTool_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MapTool_Tutorial.BP_MapTool_Tutorial_C
// 0x0010 (0x03E0 - 0x03D0)
class ABP_MapTool_Tutorial_C final : public ABP_MapTool_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_MapTool_Tutorial_C;              // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          CanOpenMap;                                        // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_MapTool_Tutorial(int32 EntryPoint);
	void EquipToolInternal();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MapTool_Tutorial_C">();
	}
	static class ABP_MapTool_Tutorial_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MapTool_Tutorial_C>();
	}
};
static_assert(alignof(ABP_MapTool_Tutorial_C) == 0x000008, "Wrong alignment on ABP_MapTool_Tutorial_C");
static_assert(sizeof(ABP_MapTool_Tutorial_C) == 0x0003E0, "Wrong size on ABP_MapTool_Tutorial_C");
static_assert(offsetof(ABP_MapTool_Tutorial_C, UberGraphFrame_BP_MapTool_Tutorial_C) == 0x0003D0, "Member 'ABP_MapTool_Tutorial_C::UberGraphFrame_BP_MapTool_Tutorial_C' has a wrong offset!");
static_assert(offsetof(ABP_MapTool_Tutorial_C, CanOpenMap) == 0x0003D8, "Member 'ABP_MapTool_Tutorial_C::CanOpenMap' has a wrong offset!");

}

