#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Poisons_TEMP_PoC

#include "Basic.hpp"

#include "S_HC_Poison_structs.hpp"


namespace SDK::Params
{

// Function BP_Poisons_TEMP_PoC.BP_Poisons_TEMP_PoC_C.ExecuteUbergraph_BP_Poisons_TEMP_PoC
// 0x0070 (0x0070 - 0x0000)
struct BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_HealingComponent_C*                 K2Node_CustomEvent_HealingComponent;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHumanCharacter*                        K2Node_CustomEvent_InstigatingCharacter;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 K2Node_CustomEvent_InstigatingItem;                // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameInstance*                          CallFunc_GetGameInstance_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FS_HC_Poison                           K2Node_MakeStruct_S_HC_Poison;                     // 0x0028(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_GameInstance_C*                     K2Node_DynamicCast_AsBP_Game_Instance;             // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FS_HC_Poison                           K2Node_MakeStruct_S_HC_Poison_1;                   // 0x0050(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue;        // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ClassClass_ReturnValue_1;      // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC) == 0x000008, "Wrong alignment on BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC");
static_assert(sizeof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC) == 0x000070, "Wrong size on BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, EntryPoint) == 0x000000, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_CustomEvent_HealingComponent) == 0x000008, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_CustomEvent_HealingComponent' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_CustomEvent_InstigatingCharacter) == 0x000010, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_CustomEvent_InstigatingCharacter' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_CustomEvent_InstigatingItem) == 0x000018, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_CustomEvent_InstigatingItem' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, CallFunc_GetGameInstance_ReturnValue) == 0x000020, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::CallFunc_GetGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_MakeStruct_S_HC_Poison) == 0x000028, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_MakeStruct_S_HC_Poison' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_DynamicCast_AsBP_Game_Instance) == 0x000040, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_DynamicCast_AsBP_Game_Instance' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_DynamicCast_bSuccess) == 0x000048, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, K2Node_MakeStruct_S_HC_Poison_1) == 0x000050, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::K2Node_MakeStruct_S_HC_Poison_1' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, CallFunc_EqualEqual_ClassClass_ReturnValue) == 0x000068, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::CallFunc_EqualEqual_ClassClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC, CallFunc_EqualEqual_ClassClass_ReturnValue_1) == 0x000069, "Member 'BP_Poisons_TEMP_PoC_C_ExecuteUbergraph_BP_Poisons_TEMP_PoC::CallFunc_EqualEqual_ClassClass_ReturnValue_1' has a wrong offset!");

// Function BP_Poisons_TEMP_PoC.BP_Poisons_TEMP_PoC_C.ApplyPoisonFromItem
// 0x0018 (0x0018 - 0x0000)
struct BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem final
{
public:
	class UBP_HealingComponent_C*                 HealingComponent;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AHumanCharacter*                        InstigatingCharacter;                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 InstigatingItem;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem) == 0x000008, "Wrong alignment on BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem");
static_assert(sizeof(BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem) == 0x000018, "Wrong size on BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem, HealingComponent) == 0x000000, "Member 'BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem::HealingComponent' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem, InstigatingCharacter) == 0x000008, "Member 'BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem::InstigatingCharacter' has a wrong offset!");
static_assert(offsetof(BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem, InstigatingItem) == 0x000010, "Member 'BP_Poisons_TEMP_PoC_C_ApplyPoisonFromItem::InstigatingItem' has a wrong offset!");

}

