#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PCComponent_ADM_CallIn_Timed

#include "Basic.hpp"

#include "BP_PCComponent_ADM_CallIn_Timed_classes.hpp"
#include "BP_PCComponent_ADM_CallIn_Timed_parameters.hpp"


namespace SDK
{

// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.ExecuteUbergraph_BP_PCComponent_ADM_CallIn_Timed
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PCComponent_ADM_CallIn_Timed_C::ExecuteUbergraph_BP_PCComponent_ADM_CallIn_Timed(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "ExecuteUbergraph_BP_PCComponent_ADM_CallIn_Timed");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_ExecuteUbergraph_BP_PCComponent_ADM_CallIn_Timed Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Update Text Timer
// (BlueprintCallable, BlueprintEvent)

void UBP_PCComponent_ADM_CallIn_Timed_C::Update_Text_Timer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Update Text Timer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Finish Local Timer on Client
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void UBP_PCComponent_ADM_CallIn_Timed_C::Finish_Local_Timer_on_Client()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Finish Local Timer on Client");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Signal Airdrop
// (BlueprintCallable, BlueprintEvent)

void UBP_PCComponent_ADM_CallIn_Timed_C::Signal_Airdrop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Signal Airdrop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Set Local Timer on Client
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Remaining_Time                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Is_Paused                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PCComponent_ADM_CallIn_Timed_C::Set_Local_Timer_on_Client(float Remaining_Time, bool Is_Paused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Set Local Timer on Client");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_Set_Local_Timer_on_Client Parms{};

	Parms.Remaining_Time = Remaining_Time;
	Parms.Is_Paused = Is_Paused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Spawn Drop Zone Area Marker
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Marker_Location                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Marker_Radius                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PCComponent_ADM_CallIn_Timed_C::Spawn_Drop_Zone_Area_Marker(const struct FVector& Marker_Location, float Marker_Radius)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Spawn Drop Zone Area Marker");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_Spawn_Drop_Zone_Area_Marker Parms{};

	Parms.Marker_Location = std::move(Marker_Location);
	Parms.Marker_Radius = Marker_Radius;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Toggle Passive UI Visibility
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PCComponent_ADM_CallIn_Timed_C::Toggle_Passive_UI_Visibility(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Toggle Passive UI Visibility");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_Toggle_Passive_UI_Visibility Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Adjust Player Count for Premature Air Drop
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Delta                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PCComponent_ADM_CallIn_Timed_C::Adjust_Player_Count_for_Premature_Air_Drop(int32 Delta)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Adjust Player Count for Premature Air Drop");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_Adjust_Player_Count_for_Premature_Air_Drop Parms{};

	Parms.Delta = Delta;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PCComponent_ADM_CallIn_Timed.BP_PCComponent_ADM_CallIn_Timed_C.Toggle Local Timer on Client
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Is_Running                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PCComponent_ADM_CallIn_Timed_C::Toggle_Local_Timer_on_Client(bool Is_Running)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PCComponent_ADM_CallIn_Timed_C", "Toggle Local Timer on Client");

	Params::BP_PCComponent_ADM_CallIn_Timed_C_Toggle_Local_Timer_on_Client Parms{};

	Parms.Is_Running = Is_Running;

	UObject::ProcessEvent(Func, &Parms);
}

}

