#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rule_ReloadBreakFullAuto

#include "Basic.hpp"

#include "BP_Rule_ReloadBreakFullAuto_classes.hpp"
#include "BP_Rule_ReloadBreakFullAuto_parameters.hpp"


namespace SDK
{

// Function BP_Rule_ReloadBreakFullAuto.BP_Rule_ReloadBreakFullAuto_C.CustomReactOnInput
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AHumanPlayerController*           TargetController                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInputRule                              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EInputRule ABP_Rule_ReloadBreakFullAuto_C::CustomReactOnInput(const class AHumanPlayerController* TargetController) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rule_ReloadBreakFullAuto_C", "CustomReactOnInput");

	Params::BP_Rule_ReloadBreakFullAuto_C_CustomReactOnInput Parms{};

	Parms.TargetController = TargetController;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

