#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShelterCassetteCamera

#include "Basic.hpp"

#include "BP_ShelterCassetteCamera_classes.hpp"
#include "BP_ShelterCassetteCamera_parameters.hpp"


namespace SDK
{

// Function BP_ShelterCassetteCamera.BP_ShelterCassetteCamera_C.ExecuteUbergraph_BP_ShelterCassetteCamera
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShelterCassetteCamera_C::ExecuteUbergraph_BP_ShelterCassetteCamera(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShelterCassetteCamera_C", "ExecuteUbergraph_BP_ShelterCassetteCamera");

	Params::BP_ShelterCassetteCamera_C_ExecuteUbergraph_BP_ShelterCassetteCamera Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShelterCassetteCamera.BP_ShelterCassetteCamera_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShelterCassetteCamera_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShelterCassetteCamera_C", "ReceiveTick");

	Params::BP_ShelterCassetteCamera_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShelterCassetteCamera.BP_ShelterCassetteCamera_C.UseCassettesPreviewCamera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_PlayerController_Shelter_C*   PlayerControllerShelter                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           PreviousViewTarget_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInstantTransition                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ShelterCassetteCamera_C::UseCassettesPreviewCamera(class ABP_PlayerController_Shelter_C* PlayerControllerShelter, class AActor* PreviousViewTarget_0, bool bInstantTransition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShelterCassetteCamera_C", "UseCassettesPreviewCamera");

	Params::BP_ShelterCassetteCamera_C_UseCassettesPreviewCamera Parms{};

	Parms.PlayerControllerShelter = PlayerControllerShelter;
	Parms.PreviousViewTarget_0 = PreviousViewTarget_0;
	Parms.bInstantTransition = bInstantTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShelterCassetteCamera.BP_ShelterCassetteCamera_C.DeactivateAllCameras
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ShelterCassetteCamera_C::DeactivateAllCameras()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShelterCassetteCamera_C", "DeactivateAllCameras");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShelterCassetteCamera.BP_ShelterCassetteCamera_C.StopUsingCassettesPreviewCamera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bInstantTransition                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AActor*                           PreviousViewTarget_0                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_PlayerController_Shelter_C*   PlayerController_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShelterCassetteCamera_C::StopUsingCassettesPreviewCamera(bool bInstantTransition, class AActor* PreviousViewTarget_0, class ABP_PlayerController_Shelter_C* PlayerController_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ShelterCassetteCamera_C", "StopUsingCassettesPreviewCamera");

	Params::BP_ShelterCassetteCamera_C_StopUsingCassettesPreviewCamera Parms{};

	Parms.bInstantTransition = bInstantTransition;
	Parms.PreviousViewTarget_0 = PreviousViewTarget_0;
	Parms.PlayerController_0 = PlayerController_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

