#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StreamingRepair

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ShelterRepairBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StreamingRepair.BP_StreamingRepair_C
// 0x0040 (0x0470 - 0x0430)
class ABP_StreamingRepair_C final : public ABP_ShelterRepairBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_StreamingRepair_C;               // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Cube;                                              // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FName                                   PrevLoadedLevel;                                   // 0x0440(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   PrevLoadedLevelLight;                              // 0x0448(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLightsLoaded;                                    // 0x0450(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          IsRepairLoaded;                                    // 0x0451(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_452[0x2];                                      // 0x0452(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LoadedLevel;                                       // 0x0454(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLevelLoaded;                                     // 0x0458(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_459[0x7];                                      // 0x0459(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           UsedSublevels;                                     // 0x0460(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_StreamingRepair(int32 EntryPoint);
	void CustomEvent_0();
	void LoadSubLevelsRequired(int32 ShelterLevel, bool LoadOnlyNewLevel);
	void Event_Load_Level_Blocking(int32 NewLevel);
	void CheckForCorrectSublevels();
	void SetSublevelVisibility(bool bShouldBeVisible, int32 ShelterLevel);
	void UnloadInvisibleLevels();
	void CustomEvent_1();
	void CustomEvent();
	void EventLoadLevel_WithOverlap(int32 NextLevel);
	void OnRepairLoaded();
	void LightsLoaded();
	void LoadLevel(int32 NewLevel);
	void SetSubLevelVisibilityIfNeeded(int32 ShelterLevel, bool bNewVisibility, bool* Valid, bool* SameVisibility);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StreamingRepair_C">();
	}
	static class ABP_StreamingRepair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StreamingRepair_C>();
	}
};
static_assert(alignof(ABP_StreamingRepair_C) == 0x000008, "Wrong alignment on ABP_StreamingRepair_C");
static_assert(sizeof(ABP_StreamingRepair_C) == 0x000470, "Wrong size on ABP_StreamingRepair_C");
static_assert(offsetof(ABP_StreamingRepair_C, UberGraphFrame_BP_StreamingRepair_C) == 0x000430, "Member 'ABP_StreamingRepair_C::UberGraphFrame_BP_StreamingRepair_C' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, Cube) == 0x000438, "Member 'ABP_StreamingRepair_C::Cube' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, PrevLoadedLevel) == 0x000440, "Member 'ABP_StreamingRepair_C::PrevLoadedLevel' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, PrevLoadedLevelLight) == 0x000448, "Member 'ABP_StreamingRepair_C::PrevLoadedLevelLight' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, IsLightsLoaded) == 0x000450, "Member 'ABP_StreamingRepair_C::IsLightsLoaded' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, IsRepairLoaded) == 0x000451, "Member 'ABP_StreamingRepair_C::IsRepairLoaded' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, LoadedLevel) == 0x000454, "Member 'ABP_StreamingRepair_C::LoadedLevel' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, IsLevelLoaded) == 0x000458, "Member 'ABP_StreamingRepair_C::IsLevelLoaded' has a wrong offset!");
static_assert(offsetof(ABP_StreamingRepair_C, UsedSublevels) == 0x000460, "Member 'ABP_StreamingRepair_C::UsedSublevels' has a wrong offset!");

}

