#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShowMe_fakeItem

#include "Basic.hpp"

#include "Flame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ShowMe_fakeItem.BP_ShowMe_fakeItem_C
// 0x0008 (0x0408 - 0x0400)
class ABP_ShowMe_fakeItem_C final : public ACustomization
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0400(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ShowMe_fakeItem_C">();
	}
	static class ABP_ShowMe_fakeItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ShowMe_fakeItem_C>();
	}
};
static_assert(alignof(ABP_ShowMe_fakeItem_C) == 0x000008, "Wrong alignment on ABP_ShowMe_fakeItem_C");
static_assert(sizeof(ABP_ShowMe_fakeItem_C) == 0x000408, "Wrong size on ABP_ShowMe_fakeItem_C");
static_assert(offsetof(ABP_ShowMe_fakeItem_C, DefaultSceneRoot) == 0x000400, "Member 'ABP_ShowMe_fakeItem_C::DefaultSceneRoot' has a wrong offset!");

}

