#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Transformator_01

#include "Basic.hpp"

#include "BP_Lootable_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Transformator_01.BP_Transformator_01_C
// 0x0018 (0x03C0 - 0x03A8)
class ABP_Transformator_01_C final : public ABP_Lootable_Base_C
{
public:
	class UObstacleComponent*                     Obstacle;                                          // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Base;                                              // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Use_Base;                                          // 0x03B8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Transformator_01_C">();
	}
	static class ABP_Transformator_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Transformator_01_C>();
	}
};
static_assert(alignof(ABP_Transformator_01_C) == 0x000008, "Wrong alignment on ABP_Transformator_01_C");
static_assert(sizeof(ABP_Transformator_01_C) == 0x0003C0, "Wrong size on ABP_Transformator_01_C");
static_assert(offsetof(ABP_Transformator_01_C, Obstacle) == 0x0003A8, "Member 'ABP_Transformator_01_C::Obstacle' has a wrong offset!");
static_assert(offsetof(ABP_Transformator_01_C, Base) == 0x0003B0, "Member 'ABP_Transformator_01_C::Base' has a wrong offset!");
static_assert(offsetof(ABP_Transformator_01_C, Use_Base) == 0x0003B8, "Member 'ABP_Transformator_01_C::Use_Base' has a wrong offset!");

}

