#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_SceneCapturePurpose

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_SceneCapturePurpose.E_SceneCapturePurpose
// NumValues: 0x0007
enum class E_SceneCapturePurpose : uint8
{
	NewEnumerator4                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator2                           = 3,
	NewEnumerator3                           = 4,
	NewEnumerator5                           = 5,
	E_MAX                                    = 6,
};

}

