#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FArchetypesVoiceLines

#include "Basic.hpp"

#include "EArchetypesGroup_structs.hpp"
#include "FVoiceLine_structs.hpp"


namespace SDK
{

// UserDefinedStruct FArchetypesVoiceLines.FArchetypesVoiceLines
// 0x0050 (0x0050 - 0x0000)
struct FFArchetypesVoiceLines final
{
public:
	TMap<EArchetypesGroup, struct FFVoiceLine>    VoiceLine_5_766526534A5D0E4756346F90D7ADFDAD;      // 0x0000(0x0050)(Edit, BlueprintVisible)
};
static_assert(alignof(FFArchetypesVoiceLines) == 0x000008, "Wrong alignment on FFArchetypesVoiceLines");
static_assert(sizeof(FFArchetypesVoiceLines) == 0x000050, "Wrong size on FFArchetypesVoiceLines");
static_assert(offsetof(FFArchetypesVoiceLines, VoiceLine_5_766526534A5D0E4756346F90D7ADFDAD) == 0x000000, "Member 'FFArchetypesVoiceLines::VoiceLine_5_766526534A5D0E4756346F90D7ADFDAD' has a wrong offset!");

}

