#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shotgun_01_ABP

#include "Basic.hpp"

#include "Shotgun_01_ABP_classes.hpp"
#include "Shotgun_01_ABP_parameters.hpp"


namespace SDK
{

// Function Shotgun_01_ABP.Shotgun_01_ABP_C.ExecuteUbergraph_Shotgun_01_ABP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShotgun_01_ABP_C::ExecuteUbergraph_Shotgun_01_ABP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Shotgun_01_ABP_C", "ExecuteUbergraph_Shotgun_01_ABP");

	Params::Shotgun_01_ABP_C_ExecuteUbergraph_Shotgun_01_ABP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Shotgun_01_ABP.Shotgun_01_ABP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UShotgun_01_ABP_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Shotgun_01_ABP_C", "AnimGraph");

	Params::Shotgun_01_ABP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

