#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_RaidStatistics

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct Struct_RaidStatistics.Struct_RaidStatistics
// 0x0020 (0x0020 - 0x0000)
struct FStruct_RaidStatistics final
{
public:
	class FString                                 PlayerName_13_7C4A68D4426E38ADB55ABF8CA4CA7073;    // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	int32                                         Kills_2_B920DBA44D410A287093DFB79EB6BCD8;          // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Deaths_4_1BC3048E46E30061CE27F38C74B63468;         // 0x0014(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Objective_15_F77846334BD1C7B68378A0B50BE401FC;     // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Headshots_8_42F0790D44BE6D6828C986AB910E4FF2;      // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FStruct_RaidStatistics) == 0x000008, "Wrong alignment on FStruct_RaidStatistics");
static_assert(sizeof(FStruct_RaidStatistics) == 0x000020, "Wrong size on FStruct_RaidStatistics");
static_assert(offsetof(FStruct_RaidStatistics, PlayerName_13_7C4A68D4426E38ADB55ABF8CA4CA7073) == 0x000000, "Member 'FStruct_RaidStatistics::PlayerName_13_7C4A68D4426E38ADB55ABF8CA4CA7073' has a wrong offset!");
static_assert(offsetof(FStruct_RaidStatistics, Kills_2_B920DBA44D410A287093DFB79EB6BCD8) == 0x000010, "Member 'FStruct_RaidStatistics::Kills_2_B920DBA44D410A287093DFB79EB6BCD8' has a wrong offset!");
static_assert(offsetof(FStruct_RaidStatistics, Deaths_4_1BC3048E46E30061CE27F38C74B63468) == 0x000014, "Member 'FStruct_RaidStatistics::Deaths_4_1BC3048E46E30061CE27F38C74B63468' has a wrong offset!");
static_assert(offsetof(FStruct_RaidStatistics, Objective_15_F77846334BD1C7B68378A0B50BE401FC) == 0x000018, "Member 'FStruct_RaidStatistics::Objective_15_F77846334BD1C7B68378A0B50BE401FC' has a wrong offset!");
static_assert(offsetof(FStruct_RaidStatistics, Headshots_8_42F0790D44BE6D6828C986AB910E4FF2) == 0x00001C, "Member 'FStruct_RaidStatistics::Headshots_8_42F0790D44BE6D6828C986AB910E4FF2' has a wrong offset!");

}

