#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_BoosterTickets_SubTab

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Flame_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"
#include "EBooster_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_BoosterTickets_SubTab.UI_BoosterTickets_SubTab_C
// 0x0190 (0x0468 - 0x02D8)
class UUI_BoosterTickets_SubTab_C final : public UMenuWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_RowButtonB_C*                       Button_LobbyTickets;                               // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_RowButtonB_C*                       Button_PersonalTickets;                            // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_DoubleXP_Event_Overlap;                     // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                Input_ApplyTicket;                                 // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                Input_Cancel;                                      // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                Input_MoreInfo;                                    // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                Input_SeeInShop;                                   // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_BetterCrate;                          // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_DeathmatchBooster;                    // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_Insurance;                            // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_LoadoutTicket;                        // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_MoreLoot;                             // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Lobby_Ticket_ScoreBoost;                           // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Personal_Ticket_DoubleParts;                       // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Personal_Ticket_DoubleResources;                   // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               Personal_Ticket_DoubleXp;                          // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScrollBox*                             ScrollBox_0;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        Text_boosterRarity;                                // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        Text_boosterTitle;                                 // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        Text_LongDescription;                              // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Tickets;                            // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_BoosterTicket_Tile_C*               LastlyFocusedTicketTile;                           // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class UClass*, class FText>              TicketToLongDescription;                           // 0x0390(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UUI_IdleWidget_C*                       IdleWidget;                                        // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_BoosterTicket_ApplyMenu_C*          TicketApplySubMenu;                                // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<TSoftClassPtr<class UClass>, class FText> TicketsSoftClass_To_ShortTitles;                   // 0x03F0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         TicketsToActivate;                                 // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InOboarding;                                       // 0x0444(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_445[0x3];                                      // 0x0445(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUserWidget*                            OnboardingWidget;                                  // 0x0448(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           OnboardingOpenTimer;                               // 0x0450(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TArray<class UUI_BoosterTicket_Tile_C*>       LobbyTickets;                                      // 0x0458(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)

public:
	void ExecuteUbergraph_UI_BoosterTickets_SubTab(int32 EntryPoint);
	void UpdateLobbyTicketsTitleSizes();
	void ScrollDescription(float AxisValue);
	void OnResetToDefaultState();
	void BndEvt__UI_BoosterTickets_SubTab_Input_ApplyTicket_K2Node_ComponentBoundEvent_6_OnActionPressedEvent__DelegateSignature();
	void BndEvt__UI_BoosterTickets_SubTab_Input_Cancel_K2Node_ComponentBoundEvent_4_OnClickedEvent__DelegateSignature();
	void BndEvt__Input_MoreInfo_K2Node_ComponentBoundEvent_4_OnActionReleasedEvent__DelegateSignature();
	void ReturnFromOnboarding();
	void OpenTicketApplyMenu();
	void OpenTicketActivationMenu(int32 OwnedTicketCount, class UClass* TicketBoosterClass);
	void Remove_Ticket_Apply_Sub_Menu();
	void ActivateBoosterTicketsFinished_Event(const struct FCloudRequestResult& RequestResult, const struct FBoosterDetails& Data);
	void ActivateBoosterTickets(const class FString& BoosterTicketSku, int32 Count);
	void RemoveIdleWidget();
	void CreateIdleWidget();
	void FocusTicketIfNeeded();
	void InitializeTicketWidgets();
	void JumpIntoShop(class UClass* CosmeticShopDesiredItemToShowcase);
	void BndEvt__Input_SeeInShop_K2Node_ComponentBoundEvent_2_OnActionPressedEvent__DelegateSignature();
	void TicketPressed(class UButton* Sender);
	void OnTicketCategoryButtonFocused(class UListButtonWidget* Sender);
	void Destruct();
	void Unbind_Ticket_button_events();
	void TicketFocused(class UButton* Sender);
	void Bind_events_to_ticket_buttons();
	void BndEvt__Button_PersonalTickets_K2Node_ComponentBoundEvent_1_OnListButtonFocusEvent__DelegateSignature(class UListButtonWidget* Sender);
	void BndEvt__Button_LobbyTickets_K2Node_ComponentBoundEvent_0_OnListButtonFocusEvent__DelegateSignature(class UListButtonWidget* Sender);
	void Construct();
	void Fake_Focus_Ticket_Categories();
	void Clear_Fake_Focus_on_Ticket_Categories(class UListButtonWidget* CategoryToIgnore);
	void Update_Input_Buttons(bool SeeInStoreAvailable, bool FocusedApplicableTicket, bool PlayerHasTicketInStash, bool ActiveDoubleXP_Event);
	class UWidget* FocusPersonalTickets(EUINavigation Navigation_0);
	class UWidget* Focus_Lobby_Tickets(EUINavigation Navigation_0);

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_BoosterTickets_SubTab_C">();
	}
	static class UUI_BoosterTickets_SubTab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_BoosterTickets_SubTab_C>();
	}
};
static_assert(alignof(UUI_BoosterTickets_SubTab_C) == 0x000008, "Wrong alignment on UUI_BoosterTickets_SubTab_C");
static_assert(sizeof(UUI_BoosterTickets_SubTab_C) == 0x000468, "Wrong size on UUI_BoosterTickets_SubTab_C");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, UberGraphFrame) == 0x0002D8, "Member 'UUI_BoosterTickets_SubTab_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Button_LobbyTickets) == 0x0002E0, "Member 'UUI_BoosterTickets_SubTab_C::Button_LobbyTickets' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Button_PersonalTickets) == 0x0002E8, "Member 'UUI_BoosterTickets_SubTab_C::Button_PersonalTickets' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Canvas_DoubleXP_Event_Overlap) == 0x0002F0, "Member 'UUI_BoosterTickets_SubTab_C::Canvas_DoubleXP_Event_Overlap' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Input_ApplyTicket) == 0x0002F8, "Member 'UUI_BoosterTickets_SubTab_C::Input_ApplyTicket' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Input_Cancel) == 0x000300, "Member 'UUI_BoosterTickets_SubTab_C::Input_Cancel' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Input_MoreInfo) == 0x000308, "Member 'UUI_BoosterTickets_SubTab_C::Input_MoreInfo' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Input_SeeInShop) == 0x000310, "Member 'UUI_BoosterTickets_SubTab_C::Input_SeeInShop' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_BetterCrate) == 0x000318, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_BetterCrate' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_DeathmatchBooster) == 0x000320, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_DeathmatchBooster' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_Insurance) == 0x000328, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_Insurance' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_LoadoutTicket) == 0x000330, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_LoadoutTicket' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_MoreLoot) == 0x000338, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_MoreLoot' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Lobby_Ticket_ScoreBoost) == 0x000340, "Member 'UUI_BoosterTickets_SubTab_C::Lobby_Ticket_ScoreBoost' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Personal_Ticket_DoubleParts) == 0x000348, "Member 'UUI_BoosterTickets_SubTab_C::Personal_Ticket_DoubleParts' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Personal_Ticket_DoubleResources) == 0x000350, "Member 'UUI_BoosterTickets_SubTab_C::Personal_Ticket_DoubleResources' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Personal_Ticket_DoubleXp) == 0x000358, "Member 'UUI_BoosterTickets_SubTab_C::Personal_Ticket_DoubleXp' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, ScrollBox_0) == 0x000360, "Member 'UUI_BoosterTickets_SubTab_C::ScrollBox_0' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Text_boosterRarity) == 0x000368, "Member 'UUI_BoosterTickets_SubTab_C::Text_boosterRarity' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Text_boosterTitle) == 0x000370, "Member 'UUI_BoosterTickets_SubTab_C::Text_boosterTitle' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, Text_LongDescription) == 0x000378, "Member 'UUI_BoosterTickets_SubTab_C::Text_LongDescription' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, WidgetSwitcher_Tickets) == 0x000380, "Member 'UUI_BoosterTickets_SubTab_C::WidgetSwitcher_Tickets' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, LastlyFocusedTicketTile) == 0x000388, "Member 'UUI_BoosterTickets_SubTab_C::LastlyFocusedTicketTile' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, TicketToLongDescription) == 0x000390, "Member 'UUI_BoosterTickets_SubTab_C::TicketToLongDescription' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, IdleWidget) == 0x0003E0, "Member 'UUI_BoosterTickets_SubTab_C::IdleWidget' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, TicketApplySubMenu) == 0x0003E8, "Member 'UUI_BoosterTickets_SubTab_C::TicketApplySubMenu' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, TicketsSoftClass_To_ShortTitles) == 0x0003F0, "Member 'UUI_BoosterTickets_SubTab_C::TicketsSoftClass_To_ShortTitles' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, TicketsToActivate) == 0x000440, "Member 'UUI_BoosterTickets_SubTab_C::TicketsToActivate' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, InOboarding) == 0x000444, "Member 'UUI_BoosterTickets_SubTab_C::InOboarding' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, OnboardingWidget) == 0x000448, "Member 'UUI_BoosterTickets_SubTab_C::OnboardingWidget' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, OnboardingOpenTimer) == 0x000450, "Member 'UUI_BoosterTickets_SubTab_C::OnboardingOpenTimer' has a wrong offset!");
static_assert(offsetof(UUI_BoosterTickets_SubTab_C, LobbyTickets) == 0x000458, "Member 'UUI_BoosterTickets_SubTab_C::LobbyTickets' has a wrong offset!");

}

