#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ConfirmBuildingBoost

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ConfirmBuildingBoost.UI_ConfirmBuildingBoost_C
// 0x0080 (0x0370 - 0x02F0)
class UUI_ConfirmBuildingBoost_C final : public UModalWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFlameTextBlock*                        CrownsAmount_TXT;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_100;                                         // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_236;                                         // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_372;                                         // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_BackProgress;                                // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             RemainingTime_TXT;                                 // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RowBackground;                                     // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                UI_GamepadActionWidget_Boost;                      // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InputActionWidget_C*                UI_GamepadActionWidget_Cancel;                     // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemSlotVisual_C*                   UI_ItemSlotVisual;                                 // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Result;                                            // 0x0350(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          HasHC;                                             // 0x0351(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_352[0x6];                                      // 0x0352(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 SlotType;                                          // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FTimerHandle                           UpdateTimerHandle;                                 // 0x0360(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	int32                                         CrownCost;                                         // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_ConfirmBuildingBoost(int32 EntryPoint);
	void Return();
	void Update_UI();
	void Construct();
	void BndEvt__UI_GamepadActionWidget_158_K2Node_ComponentBoundEvent_1_OnActionPressedEvent__DelegateSignature();
	void BndEvt__UI_GamepadActionWidget_K2Node_ComponentBoundEvent_0_OnActionPressedEvent__DelegateSignature();
	void UpdateUI();
	class AStash* GetStash();
	class FText GetPossibleSavedTime(const struct FTimespan& A);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ConfirmBuildingBoost_C">();
	}
	static class UUI_ConfirmBuildingBoost_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ConfirmBuildingBoost_C>();
	}
};
static_assert(alignof(UUI_ConfirmBuildingBoost_C) == 0x000008, "Wrong alignment on UUI_ConfirmBuildingBoost_C");
static_assert(sizeof(UUI_ConfirmBuildingBoost_C) == 0x000370, "Wrong size on UUI_ConfirmBuildingBoost_C");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, UberGraphFrame) == 0x0002F0, "Member 'UUI_ConfirmBuildingBoost_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, CrownsAmount_TXT) == 0x0002F8, "Member 'UUI_ConfirmBuildingBoost_C::CrownsAmount_TXT' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Image_2) == 0x000300, "Member 'UUI_ConfirmBuildingBoost_C::Image_2' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Image_100) == 0x000308, "Member 'UUI_ConfirmBuildingBoost_C::Image_100' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Image_236) == 0x000310, "Member 'UUI_ConfirmBuildingBoost_C::Image_236' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Image_372) == 0x000318, "Member 'UUI_ConfirmBuildingBoost_C::Image_372' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Image_BackProgress) == 0x000320, "Member 'UUI_ConfirmBuildingBoost_C::Image_BackProgress' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, RemainingTime_TXT) == 0x000328, "Member 'UUI_ConfirmBuildingBoost_C::RemainingTime_TXT' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, RowBackground) == 0x000330, "Member 'UUI_ConfirmBuildingBoost_C::RowBackground' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, UI_GamepadActionWidget_Boost) == 0x000338, "Member 'UUI_ConfirmBuildingBoost_C::UI_GamepadActionWidget_Boost' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, UI_GamepadActionWidget_Cancel) == 0x000340, "Member 'UUI_ConfirmBuildingBoost_C::UI_GamepadActionWidget_Cancel' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, UI_ItemSlotVisual) == 0x000348, "Member 'UUI_ConfirmBuildingBoost_C::UI_ItemSlotVisual' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, Result) == 0x000350, "Member 'UUI_ConfirmBuildingBoost_C::Result' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, HasHC) == 0x000351, "Member 'UUI_ConfirmBuildingBoost_C::HasHC' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, SlotType) == 0x000358, "Member 'UUI_ConfirmBuildingBoost_C::SlotType' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, UpdateTimerHandle) == 0x000360, "Member 'UUI_ConfirmBuildingBoost_C::UpdateTimerHandle' has a wrong offset!");
static_assert(offsetof(UUI_ConfirmBuildingBoost_C, CrownCost) == 0x000368, "Member 'UUI_ConfirmBuildingBoost_C::CrownCost' has a wrong offset!");

}

