#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FaceChangerTile

#include "Basic.hpp"

#include "UI_FaceChangerTile_classes.hpp"
#include "UI_FaceChangerTile_parameters.hpp"


namespace SDK
{

// Function UI_FaceChangerTile.UI_FaceChangerTile_C.ExecuteUbergraph_UI_FaceChangerTile
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FaceChangerTile_C::ExecuteUbergraph_UI_FaceChangerTile(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FaceChangerTile_C", "ExecuteUbergraph_UI_FaceChangerTile");

	Params::UI_FaceChangerTile_C_ExecuteUbergraph_UI_FaceChangerTile Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FaceChangerTile.UI_FaceChangerTile_C.Event_SetTileArchetypeClass
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ArchetypeClass_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FaceChangerTile_C::Event_SetTileArchetypeClass(class UClass* ArchetypeClass_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FaceChangerTile_C", "Event_SetTileArchetypeClass");

	Params::UI_FaceChangerTile_C_Event_SetTileArchetypeClass Parms{};

	Parms.ArchetypeClass_0 = ArchetypeClass_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FaceChangerTile.UI_FaceChangerTile_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UUI_FaceChangerTile_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FaceChangerTile_C", "OnFocusLost");

	Params::UI_FaceChangerTile_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FaceChangerTile.UI_FaceChangerTile_C.OnLoaded_303A9E7341428F48F05BE78A416FE6AD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_FaceChangerTile_C::OnLoaded_303A9E7341428F48F05BE78A416FE6AD(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FaceChangerTile_C", "OnLoaded_303A9E7341428F48F05BE78A416FE6AD");

	Params::UI_FaceChangerTile_C_OnLoaded_303A9E7341428F48F05BE78A416FE6AD Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_FaceChangerTile.UI_FaceChangerTile_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FFocusEvent                      InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UUI_FaceChangerTile_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_FaceChangerTile_C", "OnFocusReceived");

	Params::UI_FaceChangerTile_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

