#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ItemSlotVisual

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ItemSlotVisual.UI_ItemSlotVisual_C
// 0x0008 (0x03D0 - 0x03C8)
class UUI_ItemSlotVisual_C final : public USlotVisual
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_UI_ItemSlotVisual(int32 EntryPoint);
	void SetCount(int32 InCount);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void SetSlotQuantityText(const class FText& InText);
	void SetSlotBackgroundColor(const struct FLinearColor& InColorAndOpacity);
	void SetSlotIcon(class UTexture2D* Texture, bool bMatchSize, float Scale);
	void SetSlotIconLocation(const struct FVector2D& In_Transform_Translation);
	void HoverIcon(bool IsHovered_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ItemSlotVisual_C">();
	}
	static class UUI_ItemSlotVisual_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ItemSlotVisual_C>();
	}
};
static_assert(alignof(UUI_ItemSlotVisual_C) == 0x000008, "Wrong alignment on UUI_ItemSlotVisual_C");
static_assert(sizeof(UUI_ItemSlotVisual_C) == 0x0003D0, "Wrong size on UUI_ItemSlotVisual_C");
static_assert(offsetof(UUI_ItemSlotVisual_C, UberGraphFrame) == 0x0003C8, "Member 'UUI_ItemSlotVisual_C::UberGraphFrame' has a wrong offset!");

}

