#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InputActionWidget

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "InputIconWindows_structs.hpp"
#include "FlameUI_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Flame_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function UI_InputActionWidget.UI_InputActionWidget_C.ExecuteUbergraph_UI_InputActionWidget
// 0x0038 (0x0038 - 0x0000)
struct UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlatformGroupDesktop_ReturnValue;       // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(int32 PlayerIndex, EInputMode InputMode)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	class UFlameGameInstance*                     CallFunc_GetFlameGameInstance_ReturnValue;         // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_PlayerIndex;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputMode                                    K2Node_CustomEvent_InputMode;                      // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget) == 0x000008, "Wrong alignment on UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget");
static_assert(sizeof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget) == 0x000038, "Wrong size on UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, EntryPoint) == 0x000000, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, CallFunc_IsPlatformGroupDesktop_ReturnValue) == 0x000004, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::CallFunc_IsPlatformGroupDesktop_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, CallFunc_GetFlameGameInstance_ReturnValue) == 0x000028, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::CallFunc_GetFlameGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, K2Node_CustomEvent_PlayerIndex) == 0x000030, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::K2Node_CustomEvent_PlayerIndex' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget, K2Node_CustomEvent_InputMode) == 0x000034, "Member 'UI_InputActionWidget_C_ExecuteUbergraph_UI_InputActionWidget::K2Node_CustomEvent_InputMode' has a wrong offset!");

// Function UI_InputActionWidget.UI_InputActionWidget_C.InputModeChanged
// 0x0008 (0x0008 - 0x0000)
struct UI_InputActionWidget_C_InputModeChanged final
{
public:
	int32                                         PlayerIndex;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputMode                                    InputMode;                                         // 0x0004(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_InputActionWidget_C_InputModeChanged) == 0x000004, "Wrong alignment on UI_InputActionWidget_C_InputModeChanged");
static_assert(sizeof(UI_InputActionWidget_C_InputModeChanged) == 0x000008, "Wrong size on UI_InputActionWidget_C_InputModeChanged");
static_assert(offsetof(UI_InputActionWidget_C_InputModeChanged, PlayerIndex) == 0x000000, "Member 'UI_InputActionWidget_C_InputModeChanged::PlayerIndex' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_InputModeChanged, InputMode) == 0x000004, "Member 'UI_InputActionWidget_C_InputModeChanged::InputMode' has a wrong offset!");

// Function UI_InputActionWidget.UI_InputActionWidget_C.SetWindowsIcon
// 0x0150 (0x0150 - 0x0000)
struct UI_InputActionWidget_C_SetWindowsIcon final
{
public:
	class FName                                   RowName;                                           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          RowFound;                                          // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UFlameGameInstance*                     CallFunc_GetFlameGameInstance_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USaveGame*                              CallFunc_GetOptionsSaveGame_ReturnValue;           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UOptionsSaveGame*                       K2Node_DynamicCast_AsOptions_Save_Game;            // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EInputIcon                                    K2Node_Select_Default;                             // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FInputIconWindows                      CallFunc_GetDataTableRowFromName_OutRow;           // 0x003B(0x0002)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue;      // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue_1;          // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FInputIconWindows                      CallFunc_GetDataTableRowFromName_OutRow_1;         // 0x003F(0x0002)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_1;    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EInputIcon                                    K2Node_Select_Default_1;                           // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_43[0x5];                                       // 0x0043(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputIconWindows                      CallFunc_GetDataTableRowFromName_OutRow_2;         // 0x0050(0x0002)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetDataTableRowFromName_ReturnValue_2;    // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_53[0x1];                                       // 0x0053(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetEnumeratorUserFriendlyName_ReturnValue; // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlatformGroupDesktop_ReturnValue;       // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Replace_ReturnValue;                      // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_1;                    // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_2;                    // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_StrStr_ReturnValue;            // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings;       // 0x00B8(0x0010)(ReferenceParm)
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item;                           // 0x00C8(0x0028)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Key_GetDisplayName_ReturnValue;           // 0x00F8(0x0018)()
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0118(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsInputActionGamepad_IsGamepad;           // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Replace_ReturnValue_3;                    // 0x0130(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_141[0x3];                                      // 0x0141(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_1;          // 0x0144(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_StrStr_ReturnValue;              // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x014E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_InputActionWidget_C_SetWindowsIcon) == 0x000008, "Wrong alignment on UI_InputActionWidget_C_SetWindowsIcon");
static_assert(sizeof(UI_InputActionWidget_C_SetWindowsIcon) == 0x000150, "Wrong size on UI_InputActionWidget_C_SetWindowsIcon");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, RowName) == 0x000000, "Member 'UI_InputActionWidget_C_SetWindowsIcon::RowName' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, RowFound) == 0x000008, "Member 'UI_InputActionWidget_C_SetWindowsIcon::RowFound' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, Temp_bool_True_if_break_was_hit_Variable) == 0x000009, "Member 'UI_InputActionWidget_C_SetWindowsIcon::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'UI_InputActionWidget_C_SetWindowsIcon::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Not_PreBool_ReturnValue) == 0x000010, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, Temp_bool_Variable) == 0x000011, "Member 'UI_InputActionWidget_C_SetWindowsIcon::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000012, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetFlameGameInstance_ReturnValue) == 0x000018, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetFlameGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetOptionsSaveGame_ReturnValue) == 0x000020, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetOptionsSaveGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, Temp_bool_Variable_1) == 0x000028, "Member 'UI_InputActionWidget_C_SetWindowsIcon::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, K2Node_DynamicCast_AsOptions_Save_Game) == 0x000030, "Member 'UI_InputActionWidget_C_SetWindowsIcon::K2Node_DynamicCast_AsOptions_Save_Game' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'UI_InputActionWidget_C_SetWindowsIcon::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, K2Node_Select_Default) == 0x000039, "Member 'UI_InputActionWidget_C_SetWindowsIcon::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00003A, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_OutRow) == 0x00003B, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_OutRow' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_ReturnValue) == 0x00003D, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_NotEqual_ByteByte_ReturnValue_1) == 0x00003E, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_NotEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_OutRow_1) == 0x00003F, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_OutRow_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_ReturnValue_1) == 0x000041, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, K2Node_Select_Default_1) == 0x000042, "Member 'UI_InputActionWidget_C_SetWindowsIcon::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetInputSettings_ReturnValue) == 0x000048, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_OutRow_2) == 0x000050, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_OutRow_2' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetDataTableRowFromName_ReturnValue_2) == 0x000052, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetDataTableRowFromName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, Temp_int_Loop_Counter_Variable) == 0x000054, "Member 'UI_InputActionWidget_C_SetWindowsIcon::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Add_IntInt_ReturnValue) == 0x000058, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetEnumeratorUserFriendlyName_ReturnValue) == 0x000060, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetEnumeratorUserFriendlyName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_IsPlatformGroupDesktop_ReturnValue) == 0x000070, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_IsPlatformGroupDesktop_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Replace_ReturnValue) == 0x000078, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Replace_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Replace_ReturnValue_1) == 0x000088, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Replace_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Replace_ReturnValue_2) == 0x000098, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Replace_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Conv_StringToName_ReturnValue) == 0x0000A8, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_EqualEqual_StrStr_ReturnValue) == 0x0000B0, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_EqualEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_GetActionMappingByName_OutMappings) == 0x0000B8, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_GetActionMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Array_Get_Item) == 0x0000C8, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Array_Length_ReturnValue) == 0x0000F0, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Less_IntInt_ReturnValue) == 0x0000F4, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Key_GetDisplayName_ReturnValue) == 0x0000F8, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Key_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_BooleanAND_ReturnValue) == 0x000110, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Conv_TextToString_ReturnValue) == 0x000118, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_IsInputActionGamepad_IsGamepad) == 0x000128, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_IsInputActionGamepad_IsGamepad' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Replace_ReturnValue_3) == 0x000130, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Replace_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Not_PreBool_ReturnValue_1) == 0x000140, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Conv_StringToName_ReturnValue_1) == 0x000144, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Conv_StringToName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_NotEqual_StrStr_ReturnValue) == 0x00014C, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_NotEqual_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_BooleanAND_ReturnValue_1) == 0x00014D, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetWindowsIcon, CallFunc_Array_IsValidIndex_ReturnValue) == 0x00014E, "Member 'UI_InputActionWidget_C_SetWindowsIcon::CallFunc_Array_IsValidIndex_ReturnValue' has a wrong offset!");

// Function UI_InputActionWidget.UI_InputActionWidget_C.SetHovered
// 0x0090 (0x0090 - 0x0000)
struct UI_InputActionWidget_C_SetHovered final
{
public:
	bool                                          IsHovered_0;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_SelectColor_ReturnValue;                  // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0018(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0040(0x0028)()
	struct FSlateColor                            K2Node_Select_Default;                             // 0x0068(0x0028)()
};
static_assert(alignof(UI_InputActionWidget_C_SetHovered) == 0x000008, "Wrong alignment on UI_InputActionWidget_C_SetHovered");
static_assert(sizeof(UI_InputActionWidget_C_SetHovered) == 0x000090, "Wrong size on UI_InputActionWidget_C_SetHovered");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, IsHovered_0) == 0x000000, "Member 'UI_InputActionWidget_C_SetHovered::IsHovered_0' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, Temp_bool_Variable) == 0x000001, "Member 'UI_InputActionWidget_C_SetHovered::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, CallFunc_SelectColor_ReturnValue) == 0x000004, "Member 'UI_InputActionWidget_C_SetHovered::CallFunc_SelectColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, K2Node_MakeStruct_SlateColor) == 0x000018, "Member 'UI_InputActionWidget_C_SetHovered::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, K2Node_MakeStruct_SlateColor_1) == 0x000040, "Member 'UI_InputActionWidget_C_SetHovered::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_SetHovered, K2Node_Select_Default) == 0x000068, "Member 'UI_InputActionWidget_C_SetHovered::K2Node_Select_Default' has a wrong offset!");

// Function UI_InputActionWidget.UI_InputActionWidget_C.IsInputActionGamepad
// 0x0018 (0x0018 - 0x0000)
struct UI_InputActionWidget_C_IsInputActionGamepad final
{
public:
	class FString                                 InputAction;                                       // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          IsGamepad;                                         // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Contains_ReturnValue;                     // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Contains_ReturnValue_1;                   // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Contains_ReturnValue_2;                   // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_InputActionWidget_C_IsInputActionGamepad) == 0x000008, "Wrong alignment on UI_InputActionWidget_C_IsInputActionGamepad");
static_assert(sizeof(UI_InputActionWidget_C_IsInputActionGamepad) == 0x000018, "Wrong size on UI_InputActionWidget_C_IsInputActionGamepad");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, InputAction) == 0x000000, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::InputAction' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, IsGamepad) == 0x000010, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::IsGamepad' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, CallFunc_Contains_ReturnValue) == 0x000011, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::CallFunc_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, CallFunc_Contains_ReturnValue_1) == 0x000012, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::CallFunc_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, CallFunc_Contains_ReturnValue_2) == 0x000013, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::CallFunc_Contains_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, CallFunc_BooleanOR_ReturnValue) == 0x000014, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_InputActionWidget_C_IsInputActionGamepad, CallFunc_BooleanOR_ReturnValue_1) == 0x000015, "Member 'UI_InputActionWidget_C_IsInputActionGamepad::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");

}

