#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InGameNewsPage

#include "Basic.hpp"

#include "Flame_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InGameNewsPage.UI_InGameNewsPage_C
// 0x0140 (0x03A0 - 0x0260)
class UUI_InGameNewsPage_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut;                                           // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Fade;                                              // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 ImageFeature;                                      // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               ImageWrapper;                                      // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_Envelope;                                      // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IMG_Letter;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Letter;                                            // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LoadingFallbackImage;                              // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        LoadingSwitcher;                                   // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         NewsContent;                                       // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        NewsTitle;                                         // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         Max_Angle_Deflection;                              // 0x02C0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Max_Translation_Offset;                            // 0x02C4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 More_Info_URL;                                     // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UUI_InGameNews_C*                       Parent_In_Game_News_Widget;                        // 0x02D8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TArray<TSoftObjectPtr<class UTexture2D>>      LetterVariations;                                  // 0x02E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 News_ID;                                           // 0x02F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	ENewsFrequency                                Display_Frequency;                                 // 0x0300(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_301[0x7];                                      // 0x0301(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FNewsDto                               News_Data;                                         // 0x0308(0x0098)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_UI_InGameNewsPage(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Initialize(const struct FNewsDto& News_Data_0, class UTexture2DDynamic* NewsImage);
	void Randomize_Transform();
	void Randomize_Texture();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InGameNewsPage_C">();
	}
	static class UUI_InGameNewsPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InGameNewsPage_C>();
	}
};
static_assert(alignof(UUI_InGameNewsPage_C) == 0x000008, "Wrong alignment on UUI_InGameNewsPage_C");
static_assert(sizeof(UUI_InGameNewsPage_C) == 0x0003A0, "Wrong size on UUI_InGameNewsPage_C");
static_assert(offsetof(UUI_InGameNewsPage_C, UberGraphFrame) == 0x000260, "Member 'UUI_InGameNewsPage_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, FadeOut) == 0x000268, "Member 'UUI_InGameNewsPage_C::FadeOut' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Fade) == 0x000270, "Member 'UUI_InGameNewsPage_C::Fade' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, ImageFeature) == 0x000278, "Member 'UUI_InGameNewsPage_C::ImageFeature' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, ImageWrapper) == 0x000280, "Member 'UUI_InGameNewsPage_C::ImageWrapper' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, IMG_Envelope) == 0x000288, "Member 'UUI_InGameNewsPage_C::IMG_Envelope' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, IMG_Letter) == 0x000290, "Member 'UUI_InGameNewsPage_C::IMG_Letter' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Letter) == 0x000298, "Member 'UUI_InGameNewsPage_C::Letter' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, LoadingFallbackImage) == 0x0002A0, "Member 'UUI_InGameNewsPage_C::LoadingFallbackImage' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, LoadingSwitcher) == 0x0002A8, "Member 'UUI_InGameNewsPage_C::LoadingSwitcher' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, NewsContent) == 0x0002B0, "Member 'UUI_InGameNewsPage_C::NewsContent' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, NewsTitle) == 0x0002B8, "Member 'UUI_InGameNewsPage_C::NewsTitle' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Max_Angle_Deflection) == 0x0002C0, "Member 'UUI_InGameNewsPage_C::Max_Angle_Deflection' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Max_Translation_Offset) == 0x0002C4, "Member 'UUI_InGameNewsPage_C::Max_Translation_Offset' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, More_Info_URL) == 0x0002C8, "Member 'UUI_InGameNewsPage_C::More_Info_URL' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Parent_In_Game_News_Widget) == 0x0002D8, "Member 'UUI_InGameNewsPage_C::Parent_In_Game_News_Widget' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, LetterVariations) == 0x0002E0, "Member 'UUI_InGameNewsPage_C::LetterVariations' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, News_ID) == 0x0002F0, "Member 'UUI_InGameNewsPage_C::News_ID' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, Display_Frequency) == 0x000300, "Member 'UUI_InGameNewsPage_C::Display_Frequency' has a wrong offset!");
static_assert(offsetof(UUI_InGameNewsPage_C, News_Data) == 0x000308, "Member 'UUI_InGameNewsPage_C::News_Data' has a wrong offset!");

}

