#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MusicPlayer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function UI_MusicPlayer.UI_MusicPlayer_C.ExecuteUbergraph_UI_MusicPlayer
// 0x00F8 (0x00F8 - 0x0000)
struct UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_PlaySelectedButton_Success;               // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13[0x5];                                       // 0x0013(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MusicTrack_C*                       K2Node_CustomEvent_Previous;                       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MusicTrack_C*                       K2Node_CustomEvent_Current;                        // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetTrackButton_Button;                    // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetTrackButton_Button_1;                  // 0x0030(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetPlayedTrackButton_SelectedTrackButton; // 0x0040(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0058(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_62[0x2];                                       // 0x0062(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_CustomEvent_AxisValue;                      // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x2];                                       // 0x006A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(float AxisValue)>              K2Node_CreateDelegate_OutputDelegate_1;            // 0x006C(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x007C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue_1;        // 0x0090(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0098(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_99[0x7];                                       // 0x0099(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x00C8(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ResetQueue_bEmptyQueue;                   // 0x00DA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlatformGroupDesktop_ReturnValue;       // 0x00DB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x00DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x00DD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DE[0x2];                                       // 0x00DE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPawnMovementComponent*                 CallFunc_GetMovementComponent_ReturnValue;         // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer");
static_assert(sizeof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer) == 0x0000F8, "Wrong size on UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, EntryPoint) == 0x000000, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_1) == 0x000011, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_PlaySelectedButton_Success) == 0x000012, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_PlaySelectedButton_Success' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CustomEvent_Previous) == 0x000018, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CustomEvent_Previous' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CustomEvent_Current) == 0x000020, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CustomEvent_Current' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetTrackButton_Button) == 0x000028, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetTrackButton_Button' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetTrackButton_Button_1) == 0x000030, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetTrackButton_Button_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_2) == 0x000038, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_3) == 0x000039, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_4) == 0x00003A, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_5) == 0x00003B, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetPlayedTrackButton_SelectedTrackButton) == 0x000040, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetPlayedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CreateDelegate_OutputDelegate) == 0x000048, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000058, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_6) == 0x000060, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_7) == 0x000061, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CustomEvent_AxisValue) == 0x000064, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CustomEvent_AxisValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Less_FloatFloat_ReturnValue) == 0x000068, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000069, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CreateDelegate_OutputDelegate_1) == 0x00006C, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CreateDelegate_OutputDelegate_2) == 0x00007C, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_K2_SetTimerDelegate_ReturnValue_1) == 0x000090, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_K2_SetTimerDelegate_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_8) == 0x000098, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Array_Get_Item) == 0x0000A0, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Array_Length_ReturnValue) == 0x0000A8, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Less_IntInt_ReturnValue) == 0x0000AC, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x0000B0, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetSelectedTrackButton_Index) == 0x0000B8, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetSelectedTrackButton_IsFound) == 0x0000BC, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_PlayAnimation_ReturnValue) == 0x0000C0, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, K2Node_CreateDelegate_OutputDelegate_3) == 0x0000C8, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_Not_PreBool_ReturnValue) == 0x0000D8, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_9) == 0x0000D9, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_ResetQueue_bEmptyQueue) == 0x0000DA, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_ResetQueue_bEmptyQueue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsPlatformGroupDesktop_ReturnValue) == 0x0000DB, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsPlatformGroupDesktop_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_10) == 0x0000DC, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_IsValid_ReturnValue_11) == 0x0000DD, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetOwningPlayer_ReturnValue) == 0x0000E0, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_K2_GetPawn_ReturnValue) == 0x0000E8, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_K2_GetPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer, CallFunc_GetMovementComponent_ReturnValue) == 0x0000F0, "Member 'UI_MusicPlayer_C_ExecuteUbergraph_UI_MusicPlayer::CallFunc_GetMovementComponent_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.LookUpDown
// 0x0004 (0x0004 - 0x0000)
struct UI_MusicPlayer_C_LookUpDown final
{
public:
	float                                         AxisValue;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_LookUpDown) == 0x000004, "Wrong alignment on UI_MusicPlayer_C_LookUpDown");
static_assert(sizeof(UI_MusicPlayer_C_LookUpDown) == 0x000004, "Wrong size on UI_MusicPlayer_C_LookUpDown");
static_assert(offsetof(UI_MusicPlayer_C_LookUpDown, AxisValue) == 0x000000, "Member 'UI_MusicPlayer_C_LookUpDown::AxisValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.Started New Song
// 0x0010 (0x0010 - 0x0000)
struct UI_MusicPlayer_C_Started_New_Song final
{
public:
	class UBP_MusicTrack_C*                       Previous;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MusicTrack_C*                       Current;                                           // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_Started_New_Song) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_Started_New_Song");
static_assert(sizeof(UI_MusicPlayer_C_Started_New_Song) == 0x000010, "Wrong size on UI_MusicPlayer_C_Started_New_Song");
static_assert(offsetof(UI_MusicPlayer_C_Started_New_Song, Previous) == 0x000000, "Member 'UI_MusicPlayer_C_Started_New_Song::Previous' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Started_New_Song, Current) == 0x000008, "Member 'UI_MusicPlayer_C_Started_New_Song::Current' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.Populate Track List
// 0x00A0 (0x00A0 - 0x0000)
struct UI_MusicPlayer_C_Populate_Track_List final
{
public:
	TArray<class UBP_MusicTrack_C*>               Tracks;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class UBP_MusicTrack_C*                       PlayedTrack;                                       // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsPlayingTrack;                                    // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SelectedIndex;                                     // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MusicTrack_C*                       CurrentTrack;                                      // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CurrentButton;                                     // 0x0028(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MusicTrack_C*                       CallFunc_Array_Get_Item;                           // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0054(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_55[0x3];                                       // 0x0055(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item_1;                         // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x007C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x007D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7E[0x2];                                       // 0x007E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Create_ReturnValue;                       // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_Populate_Track_List) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_Populate_Track_List");
static_assert(sizeof(UI_MusicPlayer_C_Populate_Track_List) == 0x0000A0, "Wrong size on UI_MusicPlayer_C_Populate_Track_List");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, Tracks) == 0x000000, "Member 'UI_MusicPlayer_C_Populate_Track_List::Tracks' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, PlayedTrack) == 0x000010, "Member 'UI_MusicPlayer_C_Populate_Track_List::PlayedTrack' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, IsPlayingTrack) == 0x000018, "Member 'UI_MusicPlayer_C_Populate_Track_List::IsPlayingTrack' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, SelectedIndex) == 0x00001C, "Member 'UI_MusicPlayer_C_Populate_Track_List::SelectedIndex' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CurrentTrack) == 0x000020, "Member 'UI_MusicPlayer_C_Populate_Track_List::CurrentTrack' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CurrentButton) == 0x000028, "Member 'UI_MusicPlayer_C_Populate_Track_List::CurrentButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, Temp_int_Loop_Counter_Variable) == 0x000030, "Member 'UI_MusicPlayer_C_Populate_Track_List::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_IsValid_ReturnValue) == 0x000034, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Add_IntInt_ReturnValue) == 0x000038, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Array_Length_ReturnValue) == 0x00003C, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Less_IntInt_ReturnValue) == 0x000040, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, Temp_int_Array_Index_Variable) == 0x000044, "Member 'UI_MusicPlayer_C_Populate_Track_List::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Array_Get_Item) == 0x000048, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, Temp_int_Array_Index_Variable_1) == 0x000050, "Member 'UI_MusicPlayer_C_Populate_Track_List::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_BooleanOR_ReturnValue) == 0x000054, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Array_Get_Item_1) == 0x000058, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Array_Length_ReturnValue_1) == 0x000060, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, Temp_int_Loop_Counter_Variable_1) == 0x000064, "Member 'UI_MusicPlayer_C_Populate_Track_List::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Less_IntInt_ReturnValue_1) == 0x000068, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Add_IntInt_ReturnValue_1) == 0x00006C, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x000070, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_GetSelectedTrackButton_Index) == 0x000078, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_GetSelectedTrackButton_IsFound) == 0x00007C, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x00007D, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Array_Add_ReturnValue) == 0x000080, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_AddChild_ReturnValue) == 0x000088, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_GetOwningPlayer_ReturnValue) == 0x000090, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_GetOwningPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Populate_Track_List, CallFunc_Create_ReturnValue) == 0x000098, "Member 'UI_MusicPlayer_C_Populate_Track_List::CallFunc_Create_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SelectTrackButton
// 0x0028 (0x0028 - 0x0000)
struct UI_MusicPlayer_C_SelectTrackButton final
{
public:
	int32                                         TrackIndex;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_SelectTrackButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_SelectTrackButton");
static_assert(sizeof(UI_MusicPlayer_C_SelectTrackButton) == 0x000028, "Wrong size on UI_MusicPlayer_C_SelectTrackButton");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, TrackIndex) == 0x000000, "Member 'UI_MusicPlayer_C_SelectTrackButton::TrackIndex' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x000008, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_GetSelectedTrackButton_Index) == 0x000010, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_GetSelectedTrackButton_IsFound) == 0x000014, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_Array_Get_Item) == 0x000018, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_Less_IntInt_ReturnValue) == 0x000024, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrackButton, CallFunc_IsValid_ReturnValue) == 0x000025, "Member 'UI_MusicPlayer_C_SelectTrackButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SelectNextTrack
// 0x0028 (0x0028 - 0x0000)
struct UI_MusicPlayer_C_SelectNextTrack final
{
public:
	int32                                         NextTrackIndex;                                    // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_SelectNextTrack) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_SelectNextTrack");
static_assert(sizeof(UI_MusicPlayer_C_SelectNextTrack) == 0x000028, "Wrong size on UI_MusicPlayer_C_SelectNextTrack");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, NextTrackIndex) == 0x000000, "Member 'UI_MusicPlayer_C_SelectNextTrack::NextTrackIndex' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x000008, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_GetSelectedTrackButton_Index) == 0x000010, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_GetSelectedTrackButton_IsFound) == 0x000014, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_IsValid_ReturnValue) == 0x00001C, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000024, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectNextTrack, CallFunc_Greater_IntInt_ReturnValue) == 0x000025, "Member 'UI_MusicPlayer_C_SelectNextTrack::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SelectPreviousTrack
// 0x0028 (0x0028 - 0x0000)
struct UI_MusicPlayer_C_SelectPreviousTrack final
{
public:
	int32                                         NextTrackIndex;                                    // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_SelectPreviousTrack) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_SelectPreviousTrack");
static_assert(sizeof(UI_MusicPlayer_C_SelectPreviousTrack) == 0x000028, "Wrong size on UI_MusicPlayer_C_SelectPreviousTrack");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, NextTrackIndex) == 0x000000, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::NextTrackIndex' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x000008, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_GetSelectedTrackButton_Index) == 0x000010, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_GetSelectedTrackButton_IsFound) == 0x000014, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_Subtract_IntInt_ReturnValue) == 0x000018, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_IsValid_ReturnValue) == 0x00001D, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SelectPreviousTrack, CallFunc_Greater_IntInt_ReturnValue) == 0x000024, "Member 'UI_MusicPlayer_C_SelectPreviousTrack::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.PlaySelectedButton
// 0x0068 (0x0068 - 0x0000)
struct UI_MusicPlayer_C_PlaySelectedButton final
{
public:
	bool                                          Success;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          NewSelectedButton;                                 // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue_1;              // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetSelectedTrackButton_SelectedTrackButton; // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetSelectedTrackButton_Index;             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetSelectedTrackButton_IsFound;           // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4D[0x3];                                       // 0x004D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_GetPlayedTrackButton_SelectedTrackButton; // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0063(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_ResetQueue_bEmptyQueue;                   // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_PlaySelectedButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_PlaySelectedButton");
static_assert(sizeof(UI_MusicPlayer_C_PlaySelectedButton) == 0x000068, "Wrong size on UI_MusicPlayer_C_PlaySelectedButton");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, Success) == 0x000000, "Member 'UI_MusicPlayer_C_PlaySelectedButton::Success' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, NewSelectedButton) == 0x000008, "Member 'UI_MusicPlayer_C_PlaySelectedButton::NewSelectedButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_PlayAnimation_ReturnValue) == 0x000010, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_PlayAnimation_ReturnValue_1) == 0x000018, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_PlayAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, Temp_int_Array_Index_Variable) == 0x000020, "Member 'UI_MusicPlayer_C_PlaySelectedButton::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_Array_Get_Item) == 0x000028, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_Array_Length_ReturnValue) == 0x000030, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_GetSelectedTrackButton_SelectedTrackButton) == 0x000038, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_GetSelectedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_GetSelectedTrackButton_Index) == 0x000040, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_GetSelectedTrackButton_Index' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_GetSelectedTrackButton_IsFound) == 0x000044, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_GetSelectedTrackButton_IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, Temp_int_Loop_Counter_Variable) == 0x000048, "Member 'UI_MusicPlayer_C_PlaySelectedButton::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_Less_IntInt_ReturnValue) == 0x00004C, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_Add_IntInt_ReturnValue) == 0x000050, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_GetPlayedTrackButton_SelectedTrackButton) == 0x000058, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_GetPlayedTrackButton_SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_IsValid_ReturnValue) == 0x000060, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000061, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_IsValid_ReturnValue_1) == 0x000062, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_IsValid_ReturnValue_2) == 0x000063, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_PlaySelectedButton, CallFunc_ResetQueue_bEmptyQueue) == 0x000064, "Member 'UI_MusicPlayer_C_PlaySelectedButton::CallFunc_ResetQueue_bEmptyQueue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.GetSelectedTrackButton
// 0x0030 (0x0030 - 0x0000)
struct UI_MusicPlayer_C_GetSelectedTrackButton final
{
public:
	class UUI_MusicPlayer_TrackButton_C*          SelectedTrackButton;                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFound;                                           // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x002D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_GetSelectedTrackButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_GetSelectedTrackButton");
static_assert(sizeof(UI_MusicPlayer_C_GetSelectedTrackButton) == 0x000030, "Wrong size on UI_MusicPlayer_C_GetSelectedTrackButton");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, SelectedTrackButton) == 0x000000, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, Index_0) == 0x000008, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::Index_0' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, IsFound) == 0x00000C, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::IsFound' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_Array_Get_Item) == 0x000018, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_Less_IntInt_ReturnValue) == 0x000024, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_IsValid_ReturnValue) == 0x00002C, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetSelectedTrackButton, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x00002D, "Member 'UI_MusicPlayer_C_GetSelectedTrackButton::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.GetPlayedTrackButton
// 0x0028 (0x0028 - 0x0000)
struct UI_MusicPlayer_C_GetPlayedTrackButton final
{
public:
	class UUI_MusicPlayer_TrackButton_C*          SelectedTrackButton;                               // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_GetPlayedTrackButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_GetPlayedTrackButton");
static_assert(sizeof(UI_MusicPlayer_C_GetPlayedTrackButton) == 0x000028, "Wrong size on UI_MusicPlayer_C_GetPlayedTrackButton");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, SelectedTrackButton) == 0x000000, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::SelectedTrackButton' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, Temp_int_Array_Index_Variable) == 0x000008, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_Array_Get_Item) == 0x000010, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_Array_Length_ReturnValue) == 0x000018, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_Less_IntInt_ReturnValue) == 0x00001C, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_Add_IntInt_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_IsValid_ReturnValue) == 0x000024, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetPlayedTrackButton, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000025, "Member 'UI_MusicPlayer_C_GetPlayedTrackButton::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.GetTrackButton
// 0x0038 (0x0038 - 0x0000)
struct UI_MusicPlayer_C_GetTrackButton final
{
public:
	class UBP_MusicTrack_C*                       MusicTrack;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UUI_MusicPlayer_TrackButton_C*          Button;                                            // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUI_MusicPlayer_TrackButton_C*          CallFunc_Array_Get_Item;                           // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_MusicPlayer_C_GetTrackButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_GetTrackButton");
static_assert(sizeof(UI_MusicPlayer_C_GetTrackButton) == 0x000038, "Wrong size on UI_MusicPlayer_C_GetTrackButton");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, MusicTrack) == 0x000000, "Member 'UI_MusicPlayer_C_GetTrackButton::MusicTrack' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, Button) == 0x000008, "Member 'UI_MusicPlayer_C_GetTrackButton::Button' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, Temp_int_Array_Index_Variable) == 0x000010, "Member 'UI_MusicPlayer_C_GetTrackButton::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_IsValid_ReturnValue) == 0x000014, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, Temp_int_Loop_Counter_Variable) == 0x000018, "Member 'UI_MusicPlayer_C_GetTrackButton::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_Array_Length_ReturnValue) == 0x000020, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_Array_Get_Item) == 0x000028, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_Less_IntInt_ReturnValue) == 0x000030, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_GetTrackButton, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000031, "Member 'UI_MusicPlayer_C_GetTrackButton::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SetIsShuffle
// 0x0050 (0x0050 - 0x0000)
struct UI_MusicPlayer_C_SetIsShuffle final
{
public:
	bool                                          IsShuffle;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0020(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0038(0x0018)()
};
static_assert(alignof(UI_MusicPlayer_C_SetIsShuffle) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_SetIsShuffle");
static_assert(sizeof(UI_MusicPlayer_C_SetIsShuffle) == 0x000050, "Wrong size on UI_MusicPlayer_C_SetIsShuffle");
static_assert(offsetof(UI_MusicPlayer_C_SetIsShuffle, IsShuffle) == 0x000000, "Member 'UI_MusicPlayer_C_SetIsShuffle::IsShuffle' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetIsShuffle, Temp_bool_Variable) == 0x000001, "Member 'UI_MusicPlayer_C_SetIsShuffle::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetIsShuffle, Temp_text_Variable) == 0x000008, "Member 'UI_MusicPlayer_C_SetIsShuffle::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetIsShuffle, Temp_text_Variable_1) == 0x000020, "Member 'UI_MusicPlayer_C_SetIsShuffle::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetIsShuffle, K2Node_Select_Default) == 0x000038, "Member 'UI_MusicPlayer_C_SetIsShuffle::K2Node_Select_Default' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SetCurrentTrackInfo
// 0x0098 (0x0098 - 0x0000)
struct UI_MusicPlayer_C_SetCurrentTrackInfo final
{
public:
	class UBP_MusicTrack_C*                       Track;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0010(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0050(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Get_Time_Text_From_Float_Text;            // 0x0060(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0078(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0092(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0093(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_SetCurrentTrackInfo) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_SetCurrentTrackInfo");
static_assert(sizeof(UI_MusicPlayer_C_SetCurrentTrackInfo) == 0x000098, "Wrong size on UI_MusicPlayer_C_SetCurrentTrackInfo");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, Track) == 0x000000, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::Track' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, Temp_byte_Variable) == 0x000008, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, CallFunc_IsValid_ReturnValue) == 0x000009, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, K2Node_MakeStruct_FormatArgumentData) == 0x000010, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, K2Node_MakeArray_Array) == 0x000050, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, CallFunc_Get_Time_Text_From_Float_Text) == 0x000060, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::CallFunc_Get_Time_Text_From_Float_Text' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, CallFunc_Format_ReturnValue) == 0x000078, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, CallFunc_TextIsEmpty_ReturnValue) == 0x000090, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, Temp_byte_Variable_1) == 0x000091, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, Temp_bool_Variable) == 0x000092, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_SetCurrentTrackInfo, K2Node_Select_Default) == 0x000093, "Member 'UI_MusicPlayer_C_SetCurrentTrackInfo::K2Node_Select_Default' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.UpdateTrackTime
// 0x0060 (0x0060 - 0x0000)
struct UI_MusicPlayer_C_UpdateTrackTime final
{
public:
	class UBP_MusicTrack_C*                       CurrentTrack;                                      // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TotalTime;                                         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurrentTime;                                       // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Get_Time_Text_From_Float_Text;            // 0x0010(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x2];                                       // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetTimeSeconds_ReturnValue;               // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_2;        // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMin_ReturnValue;                         // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FMax_ReturnValue;                         // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_UpdateTrackTime) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_UpdateTrackTime");
static_assert(sizeof(UI_MusicPlayer_C_UpdateTrackTime) == 0x000060, "Wrong size on UI_MusicPlayer_C_UpdateTrackTime");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CurrentTrack) == 0x000000, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CurrentTrack' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, TotalTime) == 0x000008, "Member 'UI_MusicPlayer_C_UpdateTrackTime::TotalTime' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CurrentTime) == 0x00000C, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CurrentTime' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Get_Time_Text_From_Float_Text) == 0x000010, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Get_Time_Text_From_Float_Text' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_IsValid_ReturnValue_1) == 0x000029, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_GetTimeSeconds_ReturnValue) == 0x00002C, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_GetTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, Temp_float_Variable) == 0x000030, "Member 'UI_MusicPlayer_C_UpdateTrackTime::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000034, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x000038, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, Temp_bool_Variable) == 0x00003C, "Member 'UI_MusicPlayer_C_UpdateTrackTime::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Add_FloatFloat_ReturnValue) == 0x000040, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Subtract_FloatFloat_ReturnValue_2) == 0x000044, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Subtract_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Less_FloatFloat_ReturnValue) == 0x000048, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_Divide_FloatFloat_ReturnValue) == 0x00004C, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_FMin_ReturnValue) == 0x000050, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_FMin_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, CallFunc_FMax_ReturnValue) == 0x000054, "Member 'UI_MusicPlayer_C_UpdateTrackTime::CallFunc_FMax_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateTrackTime, K2Node_Select_Default) == 0x000058, "Member 'UI_MusicPlayer_C_UpdateTrackTime::K2Node_Select_Default' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.Get Time Text From Float
// 0x0150 (0x0150 - 0x0000)
struct UI_MusicPlayer_C_Get_Time_Text_From_Float final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Text;                                              // 0x0008(0x0018)(Parm, OutParm)
	int32                                         Minutes;                                           // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Seconds;                                           // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0038(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0090(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_Select_Default;                             // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Multiply_IntInt_ReturnValue;              // 0x00B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x00B8(0x0018)()
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D4[0x4];                                       // 0x00D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x00D8(0x0040)(HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11C[0x4];                                      // 0x011C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0120(0x0010)(ReferenceParm)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_134[0x4];                                      // 0x0134(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0138(0x0018)()
};
static_assert(alignof(UI_MusicPlayer_C_Get_Time_Text_From_Float) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_Get_Time_Text_From_Float");
static_assert(sizeof(UI_MusicPlayer_C_Get_Time_Text_From_Float) == 0x000150, "Wrong size on UI_MusicPlayer_C_Get_Time_Text_From_Float");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, Value) == 0x000000, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::Value' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, Text) == 0x000008, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::Text' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, Minutes) == 0x000020, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::Minutes' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, Seconds) == 0x000024, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::Seconds' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, Temp_bool_Variable) == 0x000028, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Divide_FloatFloat_ReturnValue) == 0x00002C, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_FTrunc_ReturnValue) == 0x000030, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, K2Node_MakeStruct_FormatArgumentData) == 0x000038, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Less_IntInt_ReturnValue) == 0x000078, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Conv_IntToString_ReturnValue) == 0x000080, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Concat_StrStr_ReturnValue) == 0x000090, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, K2Node_Select_Default) == 0x0000A0, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Multiply_IntInt_ReturnValue) == 0x0000B0, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Multiply_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Conv_StringToText_ReturnValue) == 0x0000B8, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0000D0, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, K2Node_MakeStruct_FormatArgumentData_1) == 0x0000D8, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000118, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, K2Node_MakeArray_Array) == 0x000120, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Round_ReturnValue) == 0x000130, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Round_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_Get_Time_Text_From_Float, CallFunc_Format_ReturnValue) == 0x000138, "Member 'UI_MusicPlayer_C_Get_Time_Text_From_Float::CallFunc_Format_ReturnValue' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.UpdateBlacklistButton
// 0x0050 (0x0050 - 0x0000)
struct UI_MusicPlayer_C_UpdateBlacklistButton final
{
public:
	bool                                          bIsBlacklisted;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0008(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0020(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x0038(0x0018)()
};
static_assert(alignof(UI_MusicPlayer_C_UpdateBlacklistButton) == 0x000008, "Wrong alignment on UI_MusicPlayer_C_UpdateBlacklistButton");
static_assert(sizeof(UI_MusicPlayer_C_UpdateBlacklistButton) == 0x000050, "Wrong size on UI_MusicPlayer_C_UpdateBlacklistButton");
static_assert(offsetof(UI_MusicPlayer_C_UpdateBlacklistButton, bIsBlacklisted) == 0x000000, "Member 'UI_MusicPlayer_C_UpdateBlacklistButton::bIsBlacklisted' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateBlacklistButton, Temp_bool_Variable) == 0x000001, "Member 'UI_MusicPlayer_C_UpdateBlacklistButton::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateBlacklistButton, Temp_text_Variable) == 0x000008, "Member 'UI_MusicPlayer_C_UpdateBlacklistButton::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateBlacklistButton, Temp_text_Variable_1) == 0x000020, "Member 'UI_MusicPlayer_C_UpdateBlacklistButton::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_MusicPlayer_C_UpdateBlacklistButton, K2Node_Select_Default) == 0x000038, "Member 'UI_MusicPlayer_C_UpdateBlacklistButton::K2Node_Select_Default' has a wrong offset!");

// Function UI_MusicPlayer.UI_MusicPlayer_C.SelectTrack
// 0x0004 (0x0004 - 0x0000)
struct UI_MusicPlayer_C_SelectTrack final
{
public:
	int32                                         TrackIndex;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_MusicPlayer_C_SelectTrack) == 0x000004, "Wrong alignment on UI_MusicPlayer_C_SelectTrack");
static_assert(sizeof(UI_MusicPlayer_C_SelectTrack) == 0x000004, "Wrong size on UI_MusicPlayer_C_SelectTrack");
static_assert(offsetof(UI_MusicPlayer_C_SelectTrack, TrackIndex) == 0x000000, "Member 'UI_MusicPlayer_C_SelectTrack::TrackIndex' has a wrong offset!");

}

