#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MapMarkerLabel

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MapMarkerLabel.UI_MapMarkerLabel_C
// 0x0028 (0x02E0 - 0x02B8)
class UUI_MapMarkerLabel_C final : public UFlameWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class URichTextBlock*                         RichTextBlock;                                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Text;                                              // 0x02C8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void ExecuteUbergraph_UI_MapMarkerLabel(int32 EntryPoint);
	void Construct();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MapMarkerLabel_C">();
	}
	static class UUI_MapMarkerLabel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MapMarkerLabel_C>();
	}
};
static_assert(alignof(UUI_MapMarkerLabel_C) == 0x000008, "Wrong alignment on UUI_MapMarkerLabel_C");
static_assert(sizeof(UUI_MapMarkerLabel_C) == 0x0002E0, "Wrong size on UUI_MapMarkerLabel_C");
static_assert(offsetof(UUI_MapMarkerLabel_C, UberGraphFrame) == 0x0002B8, "Member 'UUI_MapMarkerLabel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_MapMarkerLabel_C, RichTextBlock) == 0x0002C0, "Member 'UUI_MapMarkerLabel_C::RichTextBlock' has a wrong offset!");
static_assert(offsetof(UUI_MapMarkerLabel_C, Text) == 0x0002C8, "Member 'UUI_MapMarkerLabel_C::Text' has a wrong offset!");

}

