#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PersistentIcon

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_PersistentIcon.UI_PersistentIcon_C.ExecuteUbergraph_UI_PersistentIcon
// 0x0008 (0x0008 - 0x0000)
struct UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon) == 0x000004, "Wrong alignment on UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon");
static_assert(sizeof(UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon) == 0x000008, "Wrong size on UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon");
static_assert(offsetof(UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon, EntryPoint) == 0x000000, "Member 'UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon, K2Node_Event_IsDesignTime) == 0x000004, "Member 'UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon, CallFunc_IsValid_ReturnValue) == 0x000005, "Member 'UI_PersistentIcon_C_ExecuteUbergraph_UI_PersistentIcon::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function UI_PersistentIcon.UI_PersistentIcon_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_PersistentIcon_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(UI_PersistentIcon_C_PreConstruct) == 0x000001, "Wrong alignment on UI_PersistentIcon_C_PreConstruct");
static_assert(sizeof(UI_PersistentIcon_C_PreConstruct) == 0x000001, "Wrong size on UI_PersistentIcon_C_PreConstruct");
static_assert(offsetof(UI_PersistentIcon_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_PersistentIcon_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_PersistentIcon.UI_PersistentIcon_C.Set Progress
// 0x0010 (0x0010 - 0x0000)
struct UI_PersistentIcon_C_Set_Progress final
{
public:
	float                                         Progress;                                          // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_PersistentIcon_C_Set_Progress) == 0x000008, "Wrong alignment on UI_PersistentIcon_C_Set_Progress");
static_assert(sizeof(UI_PersistentIcon_C_Set_Progress) == 0x000010, "Wrong size on UI_PersistentIcon_C_Set_Progress");
static_assert(offsetof(UI_PersistentIcon_C_Set_Progress, Progress) == 0x000000, "Member 'UI_PersistentIcon_C_Set_Progress::Progress' has a wrong offset!");
static_assert(offsetof(UI_PersistentIcon_C_Set_Progress, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'UI_PersistentIcon_C_Set_Progress::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_PersistentIcon_C_Set_Progress, CallFunc_IsValid_ReturnValue_1) == 0x000005, "Member 'UI_PersistentIcon_C_Set_Progress::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(UI_PersistentIcon_C_Set_Progress, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000008, "Member 'UI_PersistentIcon_C_Set_Progress::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");

}

