#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SwapWeaponsWidget

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SwapWeaponsWidget.UI_SwapWeaponsWidget_C
// 0x0020 (0x0338 - 0x0318)
class UUI_SwapWeaponsWidget_C final : public USwapWeaponsWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0318(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUI_InputActionWidget_C*                ActionSwap;                                        // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_FlameSafezone_C*                    UI_FlameSafezone;                                  // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameSlot*                             FocusedSlot;                                       // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_SwapWeaponsWidget(int32 EntryPoint);
	void BndEvt__UI_SwapWeaponsWidget_WeaponSlotB_K2Node_ComponentBoundEvent_2_OnChildFocusReceived__DelegateSignature(class UWidget* Widget);
	void BndEvt__UI_SwapWeaponsWidget_WeaponSlotA_K2Node_ComponentBoundEvent_1_OnChildFocusReceived__DelegateSignature(class UWidget* Widget);
	void BndEvt__UI_SwapWeaponsWidget_ActionSwap_K2Node_ComponentBoundEvent_0_OnClickedEvent__DelegateSignature();

	class UWidget* GetWidgetToFocus() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SwapWeaponsWidget_C">();
	}
	static class UUI_SwapWeaponsWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SwapWeaponsWidget_C>();
	}
};
static_assert(alignof(UUI_SwapWeaponsWidget_C) == 0x000008, "Wrong alignment on UUI_SwapWeaponsWidget_C");
static_assert(sizeof(UUI_SwapWeaponsWidget_C) == 0x000338, "Wrong size on UUI_SwapWeaponsWidget_C");
static_assert(offsetof(UUI_SwapWeaponsWidget_C, UberGraphFrame) == 0x000318, "Member 'UUI_SwapWeaponsWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_SwapWeaponsWidget_C, ActionSwap) == 0x000320, "Member 'UUI_SwapWeaponsWidget_C::ActionSwap' has a wrong offset!");
static_assert(offsetof(UUI_SwapWeaponsWidget_C, UI_FlameSafezone) == 0x000328, "Member 'UUI_SwapWeaponsWidget_C::UI_FlameSafezone' has a wrong offset!");
static_assert(offsetof(UUI_SwapWeaponsWidget_C, FocusedSlot) == 0x000330, "Member 'UUI_SwapWeaponsWidget_C::FocusedSlot' has a wrong offset!");

}

