#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_TVTDeathnatch_ScoreEvents_FeedRow

#include "Basic.hpp"

#include "Flame_classes.hpp"
#include "Struct_Gunfight_ScoreEventInfo_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_TVTDeathnatch_ScoreEvents_FeedRow.UI_TVTDeathnatch_ScoreEvents_FeedRow_C
// 0x00C8 (0x0380 - 0x02B8)
class UUI_TVTDeathnatch_ScoreEvents_FeedRow_C final : public UFlameWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeIn;                                            // 0x02C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FadeOut;                                           // 0x02C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas_Main;                                       // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         ClassicKillFeedContainer;                          // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_ScoreEvent;                                  // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RowBackground;                                     // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        Text_PointsCount;                                  // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFlameTextBlock*                        Text_ScoreEvent;                                   // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         KillFeedRowDuration;                               // 0x0300(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_304[0x4];                                      // 0x0304(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, struct FStruct_Gunfight_ScoreEventInfo> ScoreEventName_To_EventSettings;                   // 0x0308(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 CurrentStringKey;                                  // 0x0358(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 CurrentEventName;                                  // 0x0368(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UOverlay*                               ShelfOverlay;                                      // 0x0378(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_TVTDeathnatch_ScoreEvents_FeedRow(int32 EntryPoint);
	void Show();
	void StartRowLifetime();
	void Hide();
	void LifetimeEnded();
	void Finished_0B495B1540D1B1D7BE1C24A1CCCBC3DC();
	void Finished_57E4C98F473D7D8852131C84937D60D0();
	void Initialize(const class FString& EventStringKey, int32 AwardedScore);
	void UpdateContent(const class FString& EventStringKey, int32 AwardedScore);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_TVTDeathnatch_ScoreEvents_FeedRow_C">();
	}
	static class UUI_TVTDeathnatch_ScoreEvents_FeedRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_TVTDeathnatch_ScoreEvents_FeedRow_C>();
	}
};
static_assert(alignof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C) == 0x000008, "Wrong alignment on UUI_TVTDeathnatch_ScoreEvents_FeedRow_C");
static_assert(sizeof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C) == 0x000380, "Wrong size on UUI_TVTDeathnatch_ScoreEvents_FeedRow_C");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, UberGraphFrame) == 0x0002B8, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, FadeIn) == 0x0002C0, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::FadeIn' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, FadeOut) == 0x0002C8, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::FadeOut' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, Canvas_Main) == 0x0002D0, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::Canvas_Main' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, ClassicKillFeedContainer) == 0x0002D8, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::ClassicKillFeedContainer' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, Image_ScoreEvent) == 0x0002E0, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::Image_ScoreEvent' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, RowBackground) == 0x0002E8, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::RowBackground' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, Text_PointsCount) == 0x0002F0, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::Text_PointsCount' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, Text_ScoreEvent) == 0x0002F8, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::Text_ScoreEvent' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, KillFeedRowDuration) == 0x000300, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::KillFeedRowDuration' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, ScoreEventName_To_EventSettings) == 0x000308, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::ScoreEventName_To_EventSettings' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, CurrentStringKey) == 0x000358, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::CurrentStringKey' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, CurrentEventName) == 0x000368, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::CurrentEventName' has a wrong offset!");
static_assert(offsetof(UUI_TVTDeathnatch_ScoreEvents_FeedRow_C, ShelfOverlay) == 0x000378, "Member 'UUI_TVTDeathnatch_ScoreEvents_FeedRow_C::ShelfOverlay' has a wrong offset!");

}

