#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_WeaponNarrowListSlot

#include "Basic.hpp"

#include "UI_WeaponNarrowListSlot_classes.hpp"
#include "UI_WeaponNarrowListSlot_parameters.hpp"


namespace SDK
{

// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.ExecuteUbergraph_UI_WeaponNarrowListSlot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::ExecuteUbergraph_UI_WeaponNarrowListSlot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "ExecuteUbergraph_UI_WeaponNarrowListSlot");

	Params::UI_WeaponNarrowListSlot_C_ExecuteUbergraph_UI_WeaponNarrowListSlot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UButton*                          Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature(class UButton* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature");

	Params::UI_WeaponNarrowListSlot_C_BndEvt__FlameButton_0_K2Node_ComponentBoundEvent_37_OnButtonFocusEvent__DelegateSignature Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UButton*                          Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature(class UButton* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	Params::UI_WeaponNarrowListSlot_C_BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UButton*                          Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature(class UButton* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	Params::UI_WeaponNarrowListSlot_C_BndEvt__UI_WeaponNarrowListSlot_FlameButton_47_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.BndEvt__InteractButton_K2Node_ComponentBoundEvent_82_OnButtonFocusEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UButton*                          Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::BndEvt__InteractButton_K2Node_ComponentBoundEvent_82_OnButtonFocusEvent__DelegateSignature(class UButton* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "BndEvt__InteractButton_K2Node_ComponentBoundEvent_82_OnButtonFocusEvent__DelegateSignature");

	Params::UI_WeaponNarrowListSlot_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_82_OnButtonFocusEvent__DelegateSignature Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "Tick");

	Params::UI_WeaponNarrowListSlot_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.OnItemChanged
// (Event, Public, BlueprintEvent)

void UUI_WeaponNarrowListSlot_C::OnItemChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "OnItemChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.BndEvt__InteractButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UButton*                          Sender                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_WeaponNarrowListSlot_C::BndEvt__InteractButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature(class UButton* Sender)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "BndEvt__InteractButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature");

	Params::UI_WeaponNarrowListSlot_C_BndEvt__InteractButton_K2Node_ComponentBoundEvent_14_OnButtonClickedEvent__DelegateSignature Parms{};

	Parms.Sender = Sender;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.UpdateItemCount
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_WeaponNarrowListSlot_C::UpdateItemCount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "UpdateItemCount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.SetRowTint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSlateColor                      Tint                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UUI_WeaponNarrowListSlot_C::SetRowTint(const struct FSlateColor& Tint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "SetRowTint");

	Params::UI_WeaponNarrowListSlot_C_SetRowTint Parms{};

	Parms.Tint = std::move(Tint);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.UpdateWeaponName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_WeaponNarrowListSlot_C::UpdateWeaponName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "UpdateWeaponName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_WeaponNarrowListSlot.UI_WeaponNarrowListSlot_C.UpdateCaliber
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUI_WeaponNarrowListSlot_C::UpdateCaliber()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_WeaponNarrowListSlot_C", "UpdateCaliber");

	UObject::ProcessEvent(Func, nullptr);
}

}

